### ISSUE TITLE
Verbose Output/Progress?

### ISSUE THREAD

**Issue by pvanb** [xdissent/iectrl#3]
It would be nice have the option of verbose output or some indication of progress. I wasn't even sure anything was happening until I opened another console and did `iectrl status`.

**Comment by EHLOVader** [comment]
I also thought that it had stalled when trying to install.

Should this be the default mode? and offer a silent option?

Anyway, this is the command that worked successfully for me to see what was happening.

```bash
export DEBUG='iectrl:*' && iectrl install
```
